export const icons = {
  sparkles: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z"/><path d="M5 3v4"/><path d="M19 17v4"/><path d="M3 5h4"/><path d="M17 19h4"/></svg>',
  brain: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9.5 2A2.5 2.5 0 0 1 12 4.5v15a2.5 2.5 0 0 1-4.96.44 2.5 2.5 0 0 1-2.96-3.08 3 3 0 0 1-.34-5.58 2.5 2.5 0 0 1 1.32-4.24 2.5 2.5 0 0 1 1.98-3A2.5 2.5 0 0 1 9.5 2Z"/><path d="M14.5 2A2.5 2.5 0 0 0 12 4.5v15a2.5 2.5 0 0 0 4.96.44 2.5 2.5 0 0 0 2.96-3.08 3 3 0 0 0 .34-5.58 2.5 2.5 0 0 0-1.32-4.24 2.5 2.5 0 0 0-1.98-3A2.5 2.5 0 0 0 14.5 2Z"/></svg>',
  zap: '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>',
  copy: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>',
  check: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"/></svg>',
  chevronDown: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m6 9 6 6 6-6"/></svg>',
  chevronUp: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m18 15-6-6-6 6"/></svg>',
  play: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"/></svg>',
  arrowRight: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>',
  arrowLeft: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="19" y1="12" x2="5" y2="12"/><polyline points="12 19 5 12 12 5"/></svg>',
  book: '<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20"/></svg>',
  target: '<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/></svg>',
  lightbulb: '<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5"/><path d="M9 18h6"/><path d="M10 22h4"/></svg>',
  globe: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>',
};

export const disciplines = [
  { value: 'seo', label: 'SEO', icon: '🔍', desc: 'Search engine optimization' },
  { value: 'paid', label: 'Paid Media', icon: '💰', desc: 'Ads & performance marketing' },
  { value: 'lifecycle', label: 'Lifecycle', icon: '🔄', desc: 'Retention & automation' },
  { value: 'content', label: 'Content', icon: '✍️', desc: 'Content marketing & distribution' },
  { value: 'conversion', label: 'CRO', icon: '📈', desc: 'Conversion rate optimization' },
  { value: 'linkedin', label: 'LinkedIn', icon: '💼', desc: 'Posts, carousels & engagement' },
  { value: 'blog', label: 'Blog', icon: '📝', desc: 'Long-form articles & SEO content' },
  { value: 'email', label: 'Email', icon: '📧', desc: 'Campaigns, sequences & newsletters' },
  { value: 'social', label: 'Social', icon: '📱', desc: 'Twitter, Instagram, TikTok & more' },
  { value: 'television', label: 'Television', icon: '📺', desc: 'TV commercials & broadcast' },
  { value: 'ooh', label: 'Out of Home', icon: '🏙️', desc: 'Billboards, transit & ambient' },
  { value: 'podcast', label: 'Podcast/Audio', icon: '🎙️', desc: 'Podcast ads & audio content' },
];

export const libraries: Record<string, any> = {
  seo: {
    title: "SEO — AI Prompt Library for Marketers",
    summary: "Elite SEO marketers think in systems: technical foundations, content-authority loops, and search intent mapping. They obsess over compounding returns—every piece of content builds domain authority.",
    mentalModels: [
      { name: "Content-Search Intent Fit", description: "Match content format to the user's stage in the search journey.", lesson: "A 'best X' query needs comparison content, not a product page.", source: "Eli Schwartz, Product-Led SEO (2021)" },
      { name: "Topical Authority Clusters", description: "Build interconnected content hubs that signal expertise to Google.", lesson: "One pillar page + 15-20 supporting articles outperforms 50 disconnected posts.", source: "HubSpot Topic Cluster Model (2017)" },
      { name: "The Compounding Content Effect", description: "Invest in content that grows traffic over time, not spikes.", lesson: "10% of blog posts drive 90% of traffic. Identify and double down on compounding posts.", source: "Tomasz Tunguz, Redpoint (2019)" },
      { name: "Technical SEO as Foundation", description: "No amount of content fixes crawlability and indexation issues.", lesson: "Audit site speed, crawl budget, and Core Web Vitals before scaling content.", source: "Aleyda Solis, Crawling Mondays (2020)" },
      { name: "SERP Real Estate Thinking", description: "Optimize for featured snippets, PAA boxes, and rich results.", lesson: "Position zero can drive more clicks than position one.", source: "Cyrus Shepard, Moz (2019)" },
      { name: "Link Earning vs Link Building", description: "Create assets worth linking to instead of chasing placements.", lesson: "Original research, tools, and data studies earn links passively at scale.", source: "Brian Dean, Backlinko (2016)" }
    ],
    prompts: [
      { id: 1, goal: "Keyword Clustering & Intent Mapping", prompt: "I have a list of keywords for {{BRAND}}'s {{INDUSTRY}} business. Group them into clusters based on search intent (informational, navigational, commercial, transactional). For each cluster, recommend the ideal content format and suggest a primary keyword to target. Context: {{CHALLENGE}}", whyFits: "Intent-first clustering prevents content cannibalization.", howUsed: "Run after keyword research in Ahrefs/Semrush." },
      { id: 2, goal: "Content Brief Generation", prompt: "Create a comprehensive SEO content brief for {{BRAND}} targeting their ideal customer. Include: target word count, H2/H3 structure, semantic keywords, questions to answer (from PAA), and internal linking opportunities. Business context: {{CHALLENGE}}", whyFits: "Structured briefs improve writer output and ranking probability.", howUsed: "Generate before assigning to writers." },
      { id: 3, goal: "Technical SEO Audit Prioritization", prompt: "{{BRAND}} ({{WEBSITE}}) needs to prioritize technical SEO fixes. Given their business challenge: {{CHALLENGE}}, create a 30-60-90 day remediation roadmap focusing on: crawlability, user experience, and Core Web Vitals.", whyFits: "Elite SEOs triage ruthlessly by impact.", howUsed: "Run monthly after crawl audits." },
      { id: 4, goal: "Featured Snippet Optimization", prompt: "Help {{BRAND}} win featured snippets in the {{INDUSTRY}} space. Given their challenge: {{CHALLENGE}}, identify 5 high-opportunity keywords and provide optimized content structures (paragraph, list, or table format) for each.", whyFits: "Position zero requires surgical precision.", howUsed: "Target pages ranking #2-5." },
      { id: 5, goal: "Internal Linking Architecture", prompt: "Design an internal linking strategy for {{BRAND}}'s website ({{WEBSITE}}). Identify orphan pages, high-authority pages for link equity distribution, and anchor text recommendations. Business goal: {{CHALLENGE}}", whyFits: "Internal linking is the most underrated SEO lever.", howUsed: "Run quarterly." },
      { id: 6, goal: "Content Refresh Strategy", prompt: "{{BRAND}} wants to refresh their existing content. Given their challenge: {{CHALLENGE}}, create a content decay analysis framework and prioritize which pages to update first based on traffic trends and business impact.", whyFits: "Content decay is a silent traffic killer.", howUsed: "Run quarterly on top traffic drivers." },
      { id: 7, goal: "Programmatic SEO Template", prompt: "Design a programmatic SEO strategy for {{BRAND}} in the {{INDUSTRY}} space. Create page templates for scalable content (e.g., location pages, comparison pages). Business context: {{CHALLENGE}}", whyFits: "Programmatic SEO scales to millions of pages.", howUsed: "Validate with 10-page pilot first." },
      { id: 8, goal: "Competitor Content Gap Analysis", prompt: "Analyze {{BRAND}}'s content gaps versus competitors in {{INDUSTRY}}. Identify keywords they're missing, content formats to add, and topical areas needing depth. Strategic goal: {{CHALLENGE}}", whyFits: "Competitive intelligence drives strategy.", howUsed: "Run with Ahrefs Content Gap tool." },
      { id: 9, goal: "Link-Worthy Asset Ideation", prompt: "Generate 5 link-worthy content asset ideas for {{BRAND}} in {{INDUSTRY}}. Each should be based on original data/research and useful enough to earn passive links. Business challenge: {{CHALLENGE}}", whyFits: "Links come from value, not outreach volume.", howUsed: "Brief content team on quarterly link magnets." },
      { id: 10, goal: "EEAT Signal Enhancement", prompt: "Audit {{BRAND}}'s website ({{WEBSITE}}) for Experience, Expertise, Authoritativeness, and Trustworthiness signals. Provide specific recommendations for author bios, credentials, citations, and trust badges. Context: {{CHALLENGE}}", whyFits: "EEAT is critical for YMYL niches.", howUsed: "Run on money pages." }
    ]
  },
  paid: {
    title: "Paid Media — AI Prompt Library for Marketers",
    summary: "Elite paid media operators think in systems of creative velocity, audience segmentation, and margin math. They know 80% of performance comes from creative, not targeting.",
    mentalModels: [
      { name: "Creative is the New Targeting", description: "Algorithm-driven platforms mean creative quality determines reach.", lesson: "Invest 70% of effort in creative production and testing.", source: "Alex Garcia, Marketing Examined (2023)" },
      { name: "The 3-3-3 Creative Testing Framework", description: "Test 3 hooks, 3 bodies, 3 CTAs systematically.", lesson: "Modular testing isolates variables and scales winners faster.", source: "Barry Hott, Paid Media Pro (2022)" },
      { name: "Contribution Margin Thinking", description: "Optimize for profit, not ROAS—factor in COGS and LTV.", lesson: "A 3x ROAS on a 20% margin product loses money.", source: "Taylor Holiday, CTC (2021)" },
      { name: "Creative Fatigue Curves", description: "Every ad has a decay curve—plan refresh cycles.", lesson: "Refresh creative at 3x frequency or 30% CTR decline.", source: "Sarah Sal, Facebook Ads Expert (2020)" },
      { name: "Platform-Native Creative", description: "Ads that look like content outperform polished ads.", lesson: "UGC-style, lo-fi creative often beats brand ads.", source: "Nick Shackelford (2021)" }
    ],
    prompts: [
      { id: 1, goal: "Ad Creative Hook Generation", prompt: "Generate 15 scroll-stopping hooks for {{BRAND}} in {{INDUSTRY}} targeting their ideal customer. Include: 3 curiosity hooks, 3 pain-point hooks, 3 social proof hooks, 3 contrarian hooks, 3 benefit hooks. Business challenge: {{CHALLENGE}}", whyFits: "The hook determines 80% of ad performance.", howUsed: "A/B test in Meta Ads Manager." },
      { id: 2, goal: "Audience Segmentation Strategy", prompt: "Create a tiered audience strategy for {{BRAND}}: 1) High-intent (warm), 2) Interest-based (tepid), 3) Broad (cold). For each tier, recommend budget allocation, creative approach, and expected CPAs. Goal: {{CHALLENGE}}", whyFits: "Audience architecture drives efficiency.", howUsed: "Implement as separate ad sets." },
      { id: 3, goal: "Creative Testing Roadmap", prompt: "Build a 4-week creative testing plan for {{BRAND}}. Structure each week as: hypothesis, variants to test, success metric, sample size, decision criteria. Business context: {{CHALLENGE}}", whyFits: "Systematic testing beats random iteration.", howUsed: "Execute in Meta's A/B framework." },
      { id: 4, goal: "Landing Page-Ad Message Match", prompt: "{{BRAND}} needs to improve ad-to-landing page alignment. Audit their current approach and score message match on: headline alignment, value prop consistency, visual continuity, CTA clarity. Challenge: {{CHALLENGE}}", whyFits: "Message mismatch kills conversion rates.", howUsed: "Run before launching campaigns." },
      { id: 5, goal: "Competitor Ad Intelligence", prompt: "Analyze competitor ads in {{INDUSTRY}} for {{BRAND}}. Identify: common hooks, offer structures, creative formats, and gaps to exploit. Strategic goal: {{CHALLENGE}}", whyFits: "Competitive intelligence informs differentiation.", howUsed: "Run monthly on top 5 competitors." },
      { id: 6, goal: "UGC Creator Brief", prompt: "Create a UGC video brief for {{BRAND}} targeting their ideal customer. Include: video structure (hook-problem-solution-CTA), talking points, phrases to include/avoid, ideal creator profile. Context: {{CHALLENGE}}", whyFits: "Clear briefs produce better UGC.", howUsed: "Send to creators via Billo/Insense." },
      { id: 7, goal: "Budget Allocation Optimization", prompt: "{{BRAND}} needs to optimize their paid media budget across channels. Given their goal: {{CHALLENGE}}, recommend reallocation to maximize ROI, factoring in diminishing returns and attribution windows.", whyFits: "Capital allocation is strategy.", howUsed: "Run weekly during scaling." },
      { id: 8, goal: "Retargeting Sequence Design", prompt: "Design a 14-day retargeting sequence for {{BRAND}}: Day 1-3 (reminder), Day 4-7 (objection handling), Day 8-14 (urgency). Include message angles, formats, and frequency caps. Goal: {{CHALLENGE}}", whyFits: "Sequenced retargeting prevents fatigue.", howUsed: "Build as custom audiences." },
      { id: 9, goal: "Post-iOS14 Measurement Framework", prompt: "Design a measurement framework for {{BRAND}} given signal loss. Include: first-party data strategy, server-side tracking, MMM approach, and which metrics to trust. Business context: {{CHALLENGE}}", whyFits: "Attribution is broken—triangulate.", howUsed: "Brief data team on implementation." },
      { id: 10, goal: "Creative Fatigue Diagnosis", prompt: "Help {{BRAND}} diagnose creative fatigue across their ad account. Create a framework to identify when ads start declining, what metrics signal it, and when to refresh vs retire. Challenge: {{CHALLENGE}}", whyFits: "Knowing when to kill ads matters.", howUsed: "Run weekly on top-spending ads." }
    ]
  },
  lifecycle: {
    title: "Lifecycle Marketing — AI Prompt Library for Marketers",
    summary: "Elite lifecycle marketers think in journeys, not campaigns. They architect automated experiences from acquisition to advocacy, obsessing over activation moments and retention curves.",
    mentalModels: [
      { name: "The Aha Moment Framework", description: "Identify the action that correlates with retention, then accelerate users to it.", lesson: "Facebook: 7 friends in 10 days. Find your activation metric.", source: "Chamath Palihapitiya (2013)" },
      { name: "Retention is the New Growth", description: "Focus on keeping customers before acquiring more.", lesson: "Improving retention by 5% can increase profits by 25-95%.", source: "Brian Balfour, Reforge (2017)" },
      { name: "Behavioral Cohort Segmentation", description: "Segment by actions taken, not demographics.", lesson: "Users who complete action X within 48 hours retain 3x better.", source: "Amplitude (2020)" },
      { name: "Trigger-Based > Time-Based", description: "Send messages based on user actions, not schedules.", lesson: "Behavioral triggers outperform calendar sends by 5-10x.", source: "Iterable (2022)" },
      { name: "The Reactivation Window", description: "There's an optimal window to win back churned users.", lesson: "Win-back campaigns work best 7-30 days post-churn.", source: "Klaviyo (2023)" }
    ],
    prompts: [
      { id: 1, goal: "Onboarding Sequence Architecture", prompt: "Design a 14-day onboarding sequence for {{BRAND}} mapping to: signup → first value → activation → habit formation. For each touchpoint: trigger, delay, subject line, message, CTA. Business goal: {{CHALLENGE}}", whyFits: "Onboarding is where retention is won or lost.", howUsed: "Build in Klaviyo/Customer.io." },
      { id: 2, goal: "Activation Metric Identification", prompt: "Help {{BRAND}} identify their 'aha moment'. Analyze which early user actions correlate with 30/60/90 day retention. Output: the activation metric, time window, and confidence level. Context: {{CHALLENGE}}", whyFits: "The activation metric is the north star.", howUsed: "Run analysis in Amplitude/Mixpanel." },
      { id: 3, goal: "Churn Prediction & Prevention", prompt: "Build a churn risk scoring model for {{BRAND}}. Define high/medium/low risk criteria, early warning signals, and intervention triggers. For each risk level, recommend a save campaign. Goal: {{CHALLENGE}}", whyFits: "Predicting churn before it happens is a superpower.", howUsed: "Implement in CDP." },
      { id: 4, goal: "Win-Back Campaign Strategy", prompt: "Design a win-back campaign for {{BRAND}} targeting churned users. Include: 3-email sequence, subject lines, timing, offers, and suppression rules. Business context: {{CHALLENGE}}", whyFits: "Win-back campaigns recover revenue efficiently.", howUsed: "Build as automated flow." },
      { id: 5, goal: "Behavioral Segmentation Framework", prompt: "Create a behavioral segmentation framework for {{BRAND}}. Define 5-7 segments (Power Users, At-Risk, Dormant, etc.) with criteria, messaging approach, and triggers. Challenge: {{CHALLENGE}}", whyFits: "One-size-fits-all messaging fails.", howUsed: "Implement in CDP or email platform." },
      { id: 6, goal: "Email Subject Line Testing Plan", prompt: "Generate a 4-week subject line testing plan for {{BRAND}}. Each week test one variable: personalization, urgency, curiosity, emoji, length. Include variants and success metrics. Goal: {{CHALLENGE}}", whyFits: "Subject line optimization compounds.", howUsed: "Run A/B tests in email platform." },
      { id: 7, goal: "Cross-Channel Journey Mapping", prompt: "Map the ideal customer journey for {{BRAND}} from awareness to advocacy. For each stage: primary channel, message theme, trigger, success metric, handoff. Business context: {{CHALLENGE}}", whyFits: "Journey mapping reveals gaps.", howUsed: "Visualize in Miro/Figma." },
      { id: 8, goal: "Loyalty & Referral Program", prompt: "Design a loyalty/referral program for {{BRAND}}. Include: reward structure, earning mechanics, gamification, and program economics (cost per referral, LTV lift). Goal: {{CHALLENGE}}", whyFits: "Referral programs scale efficiently.", howUsed: "Implement in ReferralCandy/custom." },
      { id: 9, goal: "Sunset Policy & List Hygiene", prompt: "Create a sunset policy for {{BRAND}}'s email list. Define engagement thresholds, re-engagement sequence, suppression criteria. Estimate deliverability impact. Context: {{CHALLENGE}}", whyFits: "List hygiene protects deliverability.", howUsed: "Implement as automated segment." },
      { id: 10, goal: "NPS-Triggered Automation", prompt: "Design NPS-triggered flows for {{BRAND}}: Promoters (referral request), Passives (feedback + follow-up), Detractors (escalation + recovery). Include timing and messaging. Goal: {{CHALLENGE}}", whyFits: "NPS is a goldmine for automation.", howUsed: "Integrate NPS tool with email." }
    ]
  },
  content: {
    title: "Content Marketing — AI Prompt Library for Marketers",
    summary: "Elite content marketers think in distribution, not just creation. They build content engines that compound—every piece serves multiple purposes across multiple channels.",
    mentalModels: [
      { name: "Distribution > Creation", description: "Spend 20% creating, 80% distributing.", lesson: "Before writing, have a distribution plan with 10+ channels.", source: "Ross Simmonds (2021)" },
      { name: "Content-Audience Fit", description: "Match format to where your audience consumes.", lesson: "LinkedIn carousel for B2B, TikTok for Gen Z.", source: "Amanda Natividad, SparkToro (2022)" },
      { name: "The Repurposing Pyramid", description: "Create one pillar piece, atomize into 10+ assets.", lesson: "One podcast = clips, quotes, blogs, threads, carousels.", source: "Gary Vaynerchuk (2019)" },
      { name: "POV-Driven Content", description: "Unique perspectives beat regurgitated information.", lesson: "Take a stance. Contrarian viewpoints earn attention.", source: "Rand Fishkin (2018)" },
      { name: "Content as Product", description: "Treat content with user research and iteration.", lesson: "Survey audience, analyze comments, iterate on data.", source: "Lenny Rachitsky (2023)" }
    ],
    prompts: [
      { id: 1, goal: "Content Pillar Development", prompt: "Define 5 content pillars for {{BRAND}} in {{INDUSTRY}}. Each pillar needs: core theme, 3 sub-topics, formats, and tie to business goals. Include example titles. Context: {{CHALLENGE}}", whyFits: "Content pillars create strategic focus.", howUsed: "Organize content calendar around pillars." },
      { id: 2, goal: "Repurposing Workflow Design", prompt: "Create a repurposing workflow for {{BRAND}}'s content. Map one pillar piece to 10+ derivatives: social posts, email snippets, video clips, infographics. Business goal: {{CHALLENGE}}", whyFits: "Repurposing multiplies content ROI.", howUsed: "Add to content SOP." },
      { id: 3, goal: "Distribution Channel Strategy", prompt: "Build a distribution strategy for {{BRAND}}'s content. List 15 channels (owned, earned, paid) with specific actions, formats, reach, and timing. Prioritize by impact. Challenge: {{CHALLENGE}}", whyFits: "Distribution determines content success.", howUsed: "Execute as post-publish checklist." },
      { id: 4, goal: "Thought Leadership Topics", prompt: "Generate 20 thought leadership content ideas for {{BRAND}} in {{INDUSTRY}}. Include: 5 contrarian takes, 5 lessons learned, 5 predictions, 5 tactical guides. Context: {{CHALLENGE}}", whyFits: "Thought leadership requires fresh angles.", howUsed: "Feed into content calendar." },
      { id: 5, goal: "Content Audit & Optimization", prompt: "Audit {{BRAND}}'s existing content ({{WEBSITE}}). Evaluate: headline strength, hook quality, structure, CTAs, SEO elements. Score each 1-10 and provide improvements. Goal: {{CHALLENGE}}", whyFits: "Optimization beats creation.", howUsed: "Run on top content quarterly." },
      { id: 6, goal: "Newsletter Value Proposition", prompt: "Design a newsletter concept for {{BRAND}}. Include: name options, tagline, content pillars, unique value prop, cadence, growth strategy, sample outline. Context: {{CHALLENGE}}", whyFits: "Newsletters are owned distribution gold.", howUsed: "Launch in Beehiiv/Substack." },
      { id: 7, goal: "Content Calendar Framework", prompt: "Build a monthly content calendar for {{BRAND}}. Include: weekly themes, content mix ratios, pillar alignment, repurposing schedule, responsibilities. Business goal: {{CHALLENGE}}", whyFits: "Calendars create consistency.", howUsed: "Implement in Notion/Airtable." },
      { id: 8, goal: "Case Study Framework", prompt: "Create a case study framework for {{BRAND}}. Include: customer selection criteria, interview questions, story structure, data points, distribution plan. Context: {{CHALLENGE}}", whyFits: "Case studies are bottom-funnel gold.", howUsed: "Use for all customer stories." },
      { id: 9, goal: "Content Performance Analysis", prompt: "Analyze content performance for {{BRAND}}. Identify: top performers and why, underperformers and diagnosis, patterns, recommendations for next quarter. Goal: {{CHALLENGE}}", whyFits: "Data-driven iteration beats guessing.", howUsed: "Run monthly/quarterly." },
      { id: 10, goal: "LinkedIn Content Strategy", prompt: "Design a LinkedIn strategy for {{BRAND}}. Include: posting frequency, content mix, engagement tactics, hashtag strategy, growth playbook. Provide 10 post ideas with hooks. Context: {{CHALLENGE}}", whyFits: "LinkedIn is B2B's highest-ROI channel.", howUsed: "Execute daily/weekly." }
    ]
  },
  conversion: {
    title: "CRO — AI Prompt Library for Marketers",
    summary: "Elite CRO practitioners think in hypotheses, not hunches. They run rigorous experiments with statistical discipline and obsess over friction reduction and compound gains.",
    mentalModels: [
      { name: "Test Everything, Trust Nothing", description: "Best practices are hypotheses until validated.", lesson: "Run your own tests—never copy blindly.", source: "Peep Laja, CXL (2018)" },
      { name: "The 80/20 of Friction", description: "80% of losses come from 20% of friction points.", lesson: "Heatmaps reveal where users struggle.", source: "Hotjar (2020)" },
      { name: "Statistical Significance or Nothing", description: "Declare winners only with 95%+ confidence.", lesson: "Calculate sample size before launching.", source: "Evan Miller (2015)" },
      { name: "Qualitative Before Quantitative", description: "User research reveals the 'why'.", lesson: "5 interviews surface more than 500K pageviews.", source: "Steve Krug (2014)" },
      { name: "Compound Conversion Gains", description: "3% x 3% x 3% = 9.3% total improvement.", lesson: "Consistent small wins compound to massive gains.", source: "Booking.com (2019)" }
    ],
    prompts: [
      { id: 1, goal: "Hypothesis Generation from Data", prompt: "Generate 10 testable CRO hypotheses for {{BRAND}} ({{WEBSITE}}). Each must include: observation, proposed change, expected impact, success metric. Prioritize by estimated impact. Challenge: {{CHALLENGE}}", whyFits: "Data-driven hypotheses outperform gut feelings.", howUsed: "Add to testing roadmap." },
      { id: 2, goal: "Landing Page Teardown", prompt: "Conduct a conversion teardown of {{BRAND}}'s landing page. Evaluate: headline clarity, value prop, social proof, CTA visibility, friction, mobile experience. Score each 1-10. Goal: {{CHALLENGE}}", whyFits: "Systematic teardowns surface hidden issues.", howUsed: "Run on key pages quarterly." },
      { id: 3, goal: "A/B Test Design Document", prompt: "Create a test design document for {{BRAND}}. Include: test name, control vs variant, primary/secondary metrics, sample size, duration, success criteria. Context: {{CHALLENGE}}", whyFits: "Proper documentation prevents failed tests.", howUsed: "Use as standard template." },
      { id: 4, goal: "Friction Audit", prompt: "Audit {{BRAND}}'s conversion funnel for friction. For each step, identify: cognitive friction, emotional friction, physical friction. Recommend changes and prioritize. Goal: {{CHALLENGE}}", whyFits: "Friction kills conversion.", howUsed: "Combine with session recordings." },
      { id: 5, goal: "User Research Questions", prompt: "Generate a user research question set for {{BRAND}} to understand why visitors don't convert. Include: 5 survey questions, 5 interview questions, 3 usability tasks. Context: {{CHALLENGE}}", whyFits: "Research uncovers the 'why'.", howUsed: "Deploy via Hotjar/Qualaroo." },
      { id: 6, goal: "Social Proof Optimization", prompt: "Audit social proof on {{BRAND}}'s site ({{WEBSITE}}). Identify gaps and recommend: testimonial formats, placement, specificity improvements, trust signals. Goal: {{CHALLENGE}}", whyFits: "Social proof is highest-leverage.", howUsed: "Brief content team on collection." },
      { id: 7, goal: "Form Optimization", prompt: "Analyze {{BRAND}}'s forms for conversion optimization. Evaluate: field necessity, labels, error handling, mobile experience. Recommend streamlined version. Context: {{CHALLENGE}}", whyFits: "Forms are conversion bottlenecks.", howUsed: "A/B test new vs original." },
      { id: 8, goal: "Pricing Page Optimization", prompt: "Audit {{BRAND}}'s pricing page. Evaluate: anchoring, feature clarity, CTA prominence, FAQ completeness, psychological pricing. Recommend changes. Goal: {{CHALLENGE}}", whyFits: "Pricing pages are high-stakes.", howUsed: "Measure revenue, not just clicks." },
      { id: 9, goal: "Mobile Conversion Audit", prompt: "Audit {{BRAND}}'s site ({{WEBSITE}}) for mobile conversion. Evaluate: tap targets, form inputs, load speed, thumb zones. Recommend mobile-specific fixes. Context: {{CHALLENGE}}", whyFits: "Mobile often converts 2-3x worse.", howUsed: "Test on actual devices." },
      { id: 10, goal: "Post-Test Analysis", prompt: "Create a post-test analysis framework for {{BRAND}}. Include: how to determine winners, why results occurred, learnings to apply, next test recommendations. Goal: {{CHALLENGE}}", whyFits: "Learning compounds faster than testing.", howUsed: "Run after every test." }
    ]
  },
  linkedin: {
    title: "LinkedIn — AI Prompt Library for Marketers",
    summary: "Elite LinkedIn creators treat the platform as a distribution engine, not a resume. They write for the algorithm first, humans second—understanding that hooks, formatting, and engagement patterns determine reach.",
    mentalModels: [
      { name: "The Hook is Everything", description: "First 2 lines determine if anyone reads the rest.", lesson: "Write 10 hooks, pick the best one. If the hook fails, the post fails.", source: "Justin Welsh, The Saturday Solopreneur (2023)" },
      { name: "Write for Skimmers", description: "Short sentences. Line breaks. White space.", lesson: "LinkedIn is mobile-first. Walls of text get scrolled past.", source: "Jasmin Alic, LinkedIn Creator (2022)" },
      { name: "The 1-9-90 Rule", description: "1% create, 9% engage, 90% lurk.", lesson: "Your audience is bigger than your engagement suggests. Lurkers become customers.", source: "Sahil Bloom (2023)" },
      { name: "Dwell Time > Likes", description: "The algorithm rewards time spent on post, not just reactions.", lesson: "Carousels and long posts with hooks keep people reading longer.", source: "Richard van der Blom, Algorithm Research (2023)" },
      { name: "Personal + Professional", description: "People follow people, not brands.", lesson: "Share failures, lessons, behind-the-scenes. Vulnerability builds trust.", source: "Chris Walker, Refine Labs (2022)" },
      { name: "Comment > Post", description: "Strategic commenting builds reach faster than posting alone.", lesson: "10 thoughtful comments on big accounts = more visibility than 1 post.", source: "Lara Acosta, LinkedIn Growth (2023)" }
    ],
    prompts: [
      { id: 1, goal: "Hook Generator", prompt: "Generate 15 scroll-stopping hooks for {{BRAND}} LinkedIn posts in {{INDUSTRY}}. Include: 3 controversial/contrarian hooks, 3 curiosity gap hooks, 3 'mistake I made' hooks, 3 data-driven hooks, 3 story-based hooks. Each must work in under 10 words. Business context: {{CHALLENGE}}", whyFits: "The hook determines 80% of post performance.", howUsed: "Save hooks in a swipe file. Test one per post." },
      { id: 2, goal: "Content Pillar Framework", prompt: "Create 5 LinkedIn content pillars for {{BRAND}} in {{INDUSTRY}}. For each pillar: theme, 5 post topics, ideal format (text/carousel/video), posting frequency. Ensure pillars tie to: {{CHALLENGE}}", whyFits: "Pillars prevent random posting and build authority.", howUsed: "Map each week to a pillar rotation." },
      { id: 3, goal: "Carousel Post Creator", prompt: "Create a 10-slide LinkedIn carousel for {{BRAND}} on a topic relevant to {{INDUSTRY}}. Include: attention-grabbing cover slide, clear takeaways per slide, visual hierarchy notes, strong CTA on final slide. Business goal: {{CHALLENGE}}", whyFits: "Carousels get 3x the reach of text posts.", howUsed: "Design in Canva, post Tuesday-Thursday." },
      { id: 4, goal: "Thought Leadership Post", prompt: "Write a LinkedIn thought leadership post for {{BRAND}}'s founder/executive. Topic should challenge conventional wisdom in {{INDUSTRY}}. Include: hook, personal story, contrarian insight, actionable takeaway. Context: {{CHALLENGE}}", whyFits: "Contrarian takes earn attention and shares.", howUsed: "Post from personal profile, not company page." },
      { id: 5, goal: "Story-Based Post", prompt: "Write a story-based LinkedIn post for {{BRAND}} using the format: Hook → Struggle → Turning point → Lesson → CTA. The story should relate to {{INDUSTRY}} and address: {{CHALLENGE}}", whyFits: "Stories create emotional connection and memorability.", howUsed: "Use for milestone moments or lessons learned." },
      { id: 6, goal: "Engagement Bait (Ethical)", prompt: "Create 5 LinkedIn posts for {{BRAND}} designed to drive comments. Include: polls, 'hot take' posts, 'which would you choose' posts, fill-in-the-blank posts. All should relate to {{INDUSTRY}}. Goal: {{CHALLENGE}}", whyFits: "Comments boost algorithmic reach more than likes.", howUsed: "Post 1-2x per week to boost overall engagement." },
      { id: 7, goal: "Company Announcement Post", prompt: "Transform this {{BRAND}} company news into an engaging LinkedIn post: {{CHALLENGE}}. Avoid corporate speak. Lead with why it matters to the reader. Include: hook, the news, what it means for customers, human element.", whyFits: "Company news needs a human angle to perform.", howUsed: "Post from founder + reshare from company page." },
      { id: 8, goal: "Weekly Content Calendar", prompt: "Create a 4-week LinkedIn content calendar for {{BRAND}}. Include: 3 posts per week, mix of formats (text, carousel, poll), content pillars, optimal posting times, engagement strategy. Business focus: {{CHALLENGE}}", whyFits: "Consistency beats sporadic viral attempts.", howUsed: "Schedule in Buffer or native LinkedIn." },
      { id: 9, goal: "Comment Strategy", prompt: "Create a LinkedIn comment strategy for {{BRAND}} in {{INDUSTRY}}. Identify: 10 accounts to engage with daily, types of comments that add value, comment templates that start conversations, time investment required. Goal: {{CHALLENGE}}", whyFits: "Strategic commenting builds network faster than posting.", howUsed: "Spend 15 min before and after posting." },
      { id: 10, goal: "Profile Optimization", prompt: "Audit and optimize the LinkedIn profile for {{BRAND}}'s key spokesperson. Include: headline formula, about section rewrite, featured section strategy, experience descriptions that sell, and CTA placement. Business context: {{CHALLENGE}}", whyFits: "Profile is your landing page—every post visitor sees it.", howUsed: "Update quarterly as positioning evolves." }
    ]
  },
  blog: {
    title: "Blog & Long-form — AI Prompt Library for Marketers",
    summary: "Elite content creators treat blogs as compounding assets, not one-off posts. They optimize for search intent, structure for skimmers, and build content moats that drive organic traffic for years.",
    mentalModels: [
      { name: "The Skyscraper Technique", description: "Find what ranks, make something 10x better.", lesson: "Don't create—improve. Find top content, then add more depth, data, and design.", source: "Brian Dean, Backlinko (2015)" },
      { name: "Search Intent Matching", description: "Google rewards content that matches what users actually want.", lesson: "A 'how to' query needs a tutorial, not a product page. Match format to intent.", source: "Ahrefs (2021)" },
      { name: "The Inverted Pyramid", description: "Lead with the answer, then provide context.", lesson: "Put the most important information first. Most readers never reach the bottom.", source: "Journalism Standard (1900s)" },
      { name: "Content-Led Growth Loops", description: "Each piece of content should generate more content opportunities.", lesson: "One pillar post → 10 spin-off articles → 50 social posts → backlinks → more traffic.", source: "Demand Curve (2022)" },
      { name: "The 80/20 of Headlines", description: "8 out of 10 people read the headline, only 2 read the rest.", lesson: "Spend 50% of writing time on the headline. Test multiple versions.", source: "David Ogilvy (1963)" },
      { name: "Compound Content", description: "Some content grows traffic over time, most decays.", lesson: "Identify evergreen topics that compound. Update them quarterly to maintain rankings.", source: "Tomasz Tunguz, Redpoint (2019)" }
    ],
    prompts: [
      { id: 1, goal: "Blog Post Outline Generator", prompt: "Create a comprehensive blog post outline for {{BRAND}} on a topic relevant to {{INDUSTRY}}. Include: SEO-optimized H1, meta description, H2/H3 structure, key points per section, internal linking opportunities, and CTA placement. Target keyword intent: {{CHALLENGE}}", whyFits: "Structured outlines produce better content faster.", howUsed: "Generate before writing. Share with writers as brief." },
      { id: 2, goal: "Headline & Hook Generator", prompt: "Generate 15 headline options for a {{BRAND}} blog post about {{CHALLENGE}} in the {{INDUSTRY}} space. Include: 3 'How to' headlines, 3 numbered list headlines, 3 question headlines, 3 controversial/contrarian headlines, 3 benefit-driven headlines. Rate each for SEO potential and click-worthiness.", whyFits: "Headlines determine 80% of whether content gets read.", howUsed: "A/B test top 2 options. Use losers for social promotion." },
      { id: 3, goal: "Introduction Hook Writer", prompt: "Write 5 compelling blog post introductions for {{BRAND}} targeting {{INDUSTRY}} readers. Use these formats: 1) Story-based, 2) Statistic-led, 3) Contrarian statement, 4) Question hook, 5) Problem-agitation. Topic/goal: {{CHALLENGE}}", whyFits: "The intro determines if readers stay or bounce.", howUsed: "Test different hooks for different content types." },
      { id: 4, goal: "Pillar Page Architecture", prompt: "Design a pillar page strategy for {{BRAND}} in {{INDUSTRY}}. Create: main pillar topic, 10-15 cluster article topics, internal linking structure, content hierarchy, and keyword targeting for each piece. Business goal: {{CHALLENGE}}", whyFits: "Pillar pages build topical authority and rank for competitive terms.", howUsed: "Plan quarterly pillar initiatives." },
      { id: 5, goal: "Content Brief Template", prompt: "Create a detailed content brief for {{BRAND}}'s writing team. Include: target keyword, search intent, competitor analysis, required sections, word count, tone guidelines, SEO requirements, internal/external linking strategy, and success metrics. Topic: {{CHALLENGE}}", whyFits: "Detailed briefs produce consistent, high-quality content.", howUsed: "Use as template for all content assignments." },
      { id: 6, goal: "Blog Post Refresher", prompt: "Create a framework for refreshing {{BRAND}}'s existing blog content. Include: criteria for selecting posts to update, checklist of elements to improve (stats, examples, structure, CTAs), SEO optimization steps, and republishing strategy. Context: {{CHALLENGE}}", whyFits: "Updating old content is often higher ROI than new content.", howUsed: "Run quarterly on top 20 traffic drivers." },
      { id: 7, goal: "Thought Leadership Article", prompt: "Outline a thought leadership article for {{BRAND}}'s CEO/founder on a contrarian topic in {{INDUSTRY}}. Include: provocative thesis, supporting arguments with data, counter-arguments addressed, personal anecdotes, and call-to-action. Goal: {{CHALLENGE}}", whyFits: "Thought leadership builds authority and earns backlinks.", howUsed: "Publish monthly from executive byline." },
      { id: 8, goal: "Listicle Framework", prompt: "Create a high-performing listicle structure for {{BRAND}} in {{INDUSTRY}}. Topic should address: {{CHALLENGE}}. Include: attention-grabbing title, intro hook, 10-15 list items with descriptions, visual/example suggestions per item, and strong conclusion with CTA.", whyFits: "Listicles are highly shareable and rank well for 'best' queries.", howUsed: "Use for comparison and resource content." },
      { id: 9, goal: "Case Study Template", prompt: "Design a case study template for {{BRAND}} to showcase customer success. Include: headline formula, challenge-solution-results structure, specific metrics to capture, quote placement, visual requirements, and distribution plan. Business context: {{CHALLENGE}}", whyFits: "Case studies are bottom-funnel conversion gold.", howUsed: "Publish 1-2 per month. Gate for lead gen." },
      { id: 10, goal: "Content Calendar Builder", prompt: "Build a 3-month blog content calendar for {{BRAND}} in {{INDUSTRY}}. Include: weekly publishing schedule, content mix (pillar/cluster/promotional), seasonal hooks, keyword targets per piece, and resource requirements. Strategic goal: {{CHALLENGE}}", whyFits: "Consistent publishing builds authority and traffic.", howUsed: "Plan quarterly. Review monthly." }
    ]
  },
  email: {
    title: "Email Campaigns — AI Prompt Library for Marketers",
    summary: "Elite email marketers think in sequences, not blasts. They architect automated journeys that nurture, convert, and retain—obsessing over subject lines, segmentation, and the metrics that actually matter: revenue per email, not open rates.",
    mentalModels: [
      { name: "The 40/40/20 Rule", description: "40% list quality, 40% offer, 20% creative.", lesson: "Don't obsess over copy if your list is bad or offer is weak. Fix fundamentals first.", source: "Ed Mayer, Direct Mail Legend (1961)" },
      { name: "One Email, One Goal", description: "Every email should have a single, clear objective.", lesson: "Multiple CTAs confuse readers. Pick one action and optimize everything for it.", source: "Joanna Wiebe, Copyhackers (2018)" },
      { name: "The Preview Text Hack", description: "Preview text is your second headline—use it.", lesson: "Preview text appears in inbox. Treat it as headline extension, not throwaway.", source: "Litmus (2020)" },
      { name: "Send Time Optimization", description: "When you send matters as much as what you send.", lesson: "Test send times by segment. B2B peaks Tuesday-Thursday 10am. B2C varies.", source: "Mailchimp Research (2022)" },
      { name: "The Value-Ask Ratio", description: "Give value 3-4 times before making an ask.", lesson: "Subscribers tolerate promotion if you've earned trust with value first.", source: "Pat Flynn, Smart Passive Income (2019)" },
      { name: "Behavior > Demographics", description: "Segment by actions, not just attributes.", lesson: "Someone who clicked 3 emails is warmer than someone who matches your ICP on paper.", source: "Klaviyo (2023)" }
    ],
    prompts: [
      { id: 1, goal: "Welcome Sequence", prompt: "Create a 5-email welcome sequence for {{BRAND}} new subscribers in {{INDUSTRY}}. For each email: subject line, preview text, body copy, CTA, and send timing. Goals: introduce brand, deliver value, build trust, soft pitch. Business context: {{CHALLENGE}}", whyFits: "Welcome emails get 4x higher open rates—first impressions matter.", howUsed: "Set up as automated flow. Trigger on signup." },
      { id: 2, goal: "Subject Line Generator", prompt: "Generate 20 subject lines for {{BRAND}}'s email campaign about {{CHALLENGE}}. Include: 4 curiosity-driven, 4 benefit-focused, 4 urgency/scarcity, 4 personalized, 4 question-based. Keep under 50 characters. Rate each for open potential.", whyFits: "Subject line determines if email gets opened at all.", howUsed: "A/B test top 2. Track winners in swipe file." },
      { id: 3, goal: "Promotional Email", prompt: "Write a promotional email for {{BRAND}} announcing {{CHALLENGE}}. Include: attention-grabbing subject line, preview text, hero section, 3 key benefits, social proof element, urgency driver, and clear CTA. Target audience: {{INDUSTRY}} professionals.", whyFits: "Promotional emails drive direct revenue when done well.", howUsed: "Send to engaged segment. Follow up with non-openers." },
      { id: 4, goal: "Re-engagement Campaign", prompt: "Create a 3-email re-engagement sequence for {{BRAND}}'s inactive subscribers (no opens in 90 days). Include: 'We miss you' angle, value reminder, final 'stay or go' email with clear choice. Goal: {{CHALLENGE}}", whyFits: "Win-back campaigns recover revenue and clean lists.", howUsed: "Automate for subscribers hitting inactivity threshold." },
      { id: 5, goal: "Newsletter Template", prompt: "Design a weekly newsletter template for {{BRAND}} in {{INDUSTRY}}. Include: recurring sections, content mix ratios, subject line formula, personalization opportunities, and engagement hooks. Newsletter should support: {{CHALLENGE}}", whyFits: "Consistent newsletters build habit and trust.", howUsed: "Use template weekly. Rotate content types." },
      { id: 6, goal: "Cart Abandonment Sequence", prompt: "Create a 3-email cart abandonment sequence for {{BRAND}}. Include: Email 1 (1hr - reminder), Email 2 (24hr - handle objections), Email 3 (72hr - urgency/incentive). Each needs subject, preview, body, and CTA. Context: {{CHALLENGE}}", whyFits: "Cart abandonment emails recover 5-15% of lost revenue.", howUsed: "Automate in e-commerce platform." },
      { id: 7, goal: "Product Launch Sequence", prompt: "Design a 5-email product launch sequence for {{BRAND}} launching to {{INDUSTRY}} audience. Include: teaser, announcement, social proof, objection handling, last chance. Each email: timing, subject, key message, CTA. Launch goal: {{CHALLENGE}}", whyFits: "Sequenced launches outperform single-send announcements.", howUsed: "Schedule around launch date. Coordinate with other channels." },
      { id: 8, goal: "Nurture Sequence", prompt: "Create a 7-email nurture sequence for {{BRAND}} leads in {{INDUSTRY}}. Map to buyer journey: awareness → consideration → decision. Each email: subject, value delivered, soft/hard CTA, timing. Goal: {{CHALLENGE}}", whyFits: "Nurtured leads produce 50% more sales at 33% lower cost.", howUsed: "Trigger on lead magnet download or form fill." },
      { id: 9, goal: "Event/Webinar Promotion", prompt: "Create an email sequence promoting {{BRAND}}'s upcoming event/webinar. Include: announcement (2 weeks), reminder (1 week), last chance (1 day), day-of reminder, follow-up with replay. Target: {{INDUSTRY}} audience. Event topic: {{CHALLENGE}}", whyFits: "Multi-touch promotion dramatically increases registration.", howUsed: "Automate based on event date." },
      { id: 10, goal: "Feedback Request Email", prompt: "Write 3 versions of a feedback/survey request email for {{BRAND}}. Include: subject line, why their input matters, what's in it for them, clear CTA to survey. Keep under 150 words. Context: {{CHALLENGE}}", whyFits: "Customer feedback drives product and content decisions.", howUsed: "Send post-purchase or post-milestone." }
    ]
  },
  social: {
    title: "Social Media — AI Prompt Library for Marketers",
    summary: "Elite social media marketers think platform-native, not cross-post. They understand each algorithm's rewards, create for mobile-first consumption, and build engaged communities—not just follower counts.",
    mentalModels: [
      { name: "Platform-Native Content", description: "What works on LinkedIn fails on TikTok and vice versa.", lesson: "Create for each platform's culture and format. Repurpose the idea, not the asset.", source: "Gary Vaynerchuk (2020)" },
      { name: "The 3-Second Rule", description: "You have 3 seconds to stop the scroll.", lesson: "Lead with movement, contrast, or pattern interrupt. Hook fast or lose them.", source: "TikTok Creator Playbook (2022)" },
      { name: "Community > Audience", description: "Audiences consume, communities participate.", lesson: "Reply to every comment. Create inside jokes. Make followers feel like insiders.", source: "David Spinks, CMX (2021)" },
      { name: "The Pareto of Posting", description: "80% of results come from 20% of content types.", lesson: "Find your winning formats and double down. Kill what doesn't work.", source: "Buffer Research (2023)" },
      { name: "Algorithm = Engagement Velocity", description: "How fast you get engagement determines reach.", lesson: "Post when your audience is active. Engage in first 30 minutes.", source: "Later (2023)" },
      { name: "The Authenticity Premium", description: "Raw and real outperforms polished and produced.", lesson: "Behind-the-scenes, fails, and unfiltered moments build trust faster than ads.", source: "Hootsuite (2023)" }
    ],
    prompts: [
      { id: 1, goal: "Twitter/X Thread Creator", prompt: "Create a viral Twitter/X thread for {{BRAND}} on a topic relevant to {{INDUSTRY}}. Include: hook tweet (under 280 chars), 8-10 value tweets, engagement tweet asking for replies, and CTA tweet. Topic should address: {{CHALLENGE}}", whyFits: "Threads get 10x the engagement of single tweets.", howUsed: "Post threads 2-3x per week. Best times: Tue-Thu 9am." },
      { id: 2, goal: "Instagram Caption Generator", prompt: "Write 10 Instagram captions for {{BRAND}} in {{INDUSTRY}}. Include: mix of storytelling, educational, behind-the-scenes, and promotional. Each caption: hook, body, CTA, and 5 relevant hashtags. Theme: {{CHALLENGE}}", whyFits: "Captions drive comments which drive reach.", howUsed: "Batch create weekly. Save hashtag sets." },
      { id: 3, goal: "TikTok/Reels Script", prompt: "Create 5 short-form video scripts (15-60 sec) for {{BRAND}} targeting {{INDUSTRY}} audience. Include: hook (first 3 sec), main content, CTA, and trending audio suggestions. Videos should address: {{CHALLENGE}}", whyFits: "Short-form video is highest-reach format in 2024.", howUsed: "Film in batches. Post 1-2x daily during testing." },
      { id: 4, goal: "Content Pillar Strategy", prompt: "Create a social media content pillar strategy for {{BRAND}} across platforms. Define 5 pillars, each with: theme, content formats, posting frequency, example posts, and how it ties to {{CHALLENGE}}", whyFits: "Pillars ensure variety while building recognizable themes.", howUsed: "Rotate pillars throughout the week." },
      { id: 5, goal: "Engagement Post Templates", prompt: "Create 10 high-engagement social media posts for {{BRAND}}. Include: polls, 'this or that', controversial opinions, fill-in-the-blank, questions, and challenges. All should relate to {{INDUSTRY}}. Goal: {{CHALLENGE}}", whyFits: "Engagement posts train the algorithm to show your content.", howUsed: "Post 2-3 engagement posts per week." },
      { id: 6, goal: "Social Media Calendar", prompt: "Build a 2-week social media calendar for {{BRAND}} across Twitter, Instagram, and LinkedIn. Include: daily posts, content types, best posting times per platform, and engagement windows. Theme: {{CHALLENGE}}", whyFits: "Consistency beats sporadic posting every time.", howUsed: "Schedule in Buffer/Hootsuite. Batch create content." },
      { id: 7, goal: "Brand Voice Guidelines", prompt: "Create social media brand voice guidelines for {{BRAND}} in {{INDUSTRY}}. Define: tone attributes, words to use/avoid, emoji usage, response templates, and examples of on-brand vs off-brand posts. Context: {{CHALLENGE}}", whyFits: "Consistent voice builds recognition and trust.", howUsed: "Share with all team members who post." },
      { id: 8, goal: "Hashtag Strategy", prompt: "Develop a hashtag strategy for {{BRAND}} on Instagram and Twitter. Include: 10 niche hashtags, 10 medium-competition hashtags, 5 broad hashtags, branded hashtag options, and hashtag groupings by content type. Industry: {{INDUSTRY}}", whyFits: "Strategic hashtags increase discoverability.", howUsed: "Save hashtag sets. Rotate to avoid shadowban." },
      { id: 9, goal: "User-Generated Content Campaign", prompt: "Design a UGC campaign for {{BRAND}} to encourage customer content creation. Include: campaign concept, hashtag, incentive structure, submission guidelines, and promotion plan. Goal: {{CHALLENGE}}", whyFits: "UGC provides social proof and free content.", howUsed: "Launch quarterly. Feature best submissions." },
      { id: 10, goal: "Crisis Response Templates", prompt: "Create social media crisis response templates for {{BRAND}}. Include: templates for negative feedback, product issues, PR situations, and tone guidelines for sensitive topics. Context: {{INDUSTRY}}", whyFits: "Prepared responses prevent panic decisions.", howUsed: "Keep in team handbook. Update as situations arise." }
    ]
  },
  television: {
    title: "Television — AI Prompt Library for Marketers",
    summary: "Elite TV advertisers think in emotional storytelling and mass reach. They understand that TV builds brands through sight, sound, and motion—creating cultural moments that drive awareness and consideration at scale.",
    mentalModels: [
      { name: "The 30-Second Story Arc", description: "Every effective TV spot has a beginning, middle, and end.", lesson: "Setup (5 sec) → Conflict/Interest (15 sec) → Resolution + Brand (10 sec).", source: "David Ogilvy, Confessions of an Advertising Man (1963)" },
      { name: "Emotional Resonance > Rational Argument", description: "TV's power is feeling, not features.", lesson: "People remember how you made them feel, not what you said.", source: "Les Binet & Peter Field, The Long and Short of It (2013)" },
      { name: "Mental Availability", description: "Brand building creates predisposition to buy.", lesson: "TV builds mental availability that pays off at the moment of purchase.", source: "Byron Sharp, How Brands Grow (2010)" },
      { name: "The Distinctive Asset Advantage", description: "Sonic logos, characters, and visual devices multiply impact.", lesson: "Consistent brand assets make ads 8x more effective.", source: "Jenni Romaniuk, Building Distinctive Brand Assets (2018)" },
      { name: "Reach and Frequency Math", description: "Effective frequency varies by objective and creative.", lesson: "Brand building needs reach; direct response needs frequency.", source: "Erwin Ephron, Recency Planning (1995)" }
    ],
    prompts: [
      { id: 1, goal: "TV Commercial Concept Development", prompt: "Develop 3 TV commercial concepts (30-second spots) for {{BRAND}} in {{INDUSTRY}}. For each: core insight, storyline, visual treatment, emotional journey, and tagline. Business challenge: {{CHALLENGE}}", whyFits: "Multiple concepts allow testing different approaches.", howUsed: "Present to creative team for storyboarding." },
      { id: 2, goal: "TV Script Writing (30 Seconds)", prompt: "Write a complete 30-second TV script for {{BRAND}}. Include: scene descriptions, dialogue, sound design, music cues, super/text overlays, and end frame. Target audience insight: {{CHALLENGE}}", whyFits: "Detailed scripts enable accurate production.", howUsed: "Brief production team or agency." },
      { id: 3, goal: "TV Script Writing (15 Seconds)", prompt: "Write a 15-second TV cutdown for {{BRAND}}. Distill the core message to its essence. Include: visual sequence, voiceover (max 35 words), sound design, and end frame. Goal: {{CHALLENGE}}", whyFits: "15-second spots require ruthless prioritization.", howUsed: "Use for frequency buys and digital extension." },
      { id: 4, goal: "Storyboard Brief", prompt: "Create a storyboard brief for {{BRAND}}'s TV spot. Include: 8-10 key frames with visual descriptions, camera movements, transitions, and accompanying audio. Context: {{CHALLENGE}}", whyFits: "Storyboards align stakeholders before production.", howUsed: "Brief storyboard artist or agency." },
      { id: 5, goal: "TV Media Strategy", prompt: "Develop a TV media strategy for {{BRAND}} in {{INDUSTRY}}. Include: target audience definition, daypart strategy, program genres, reach/frequency goals, and budget allocation (national vs local). Goal: {{CHALLENGE}}", whyFits: "Strategic media placement maximizes impact.", howUsed: "Brief media buying team." },
      { id: 6, goal: "Connected TV (CTV) Strategy", prompt: "Create a Connected TV strategy for {{BRAND}}. Include: platform recommendations (Hulu, Roku, etc.), targeting approach, creative considerations, measurement plan, and integration with linear TV. Context: {{CHALLENGE}}", whyFits: "CTV bridges TV's reach with digital's targeting.", howUsed: "Brief digital media team." },
      { id: 7, goal: "TV Campaign Measurement Framework", prompt: "Design a TV campaign measurement framework for {{BRAND}}. Include: brand lift metrics, sales attribution approach, reach verification, competitive benchmarking, and reporting cadence. Goal: {{CHALLENGE}}", whyFits: "Proving TV ROI requires multi-metric approach.", howUsed: "Set up with analytics team pre-launch." },
      { id: 8, goal: "Testimonial/Case Study Spot", prompt: "Write a customer testimonial TV script for {{BRAND}}. Include: customer selection criteria, interview questions to capture, narrative structure, b-roll requirements, and brand integration points. Context: {{CHALLENGE}}", whyFits: "Authentic testimonials build trust at scale.", howUsed: "Brief production team for customer shoots." },
      { id: 9, goal: "Brand Anthem Concept", prompt: "Develop a brand anthem (60-second) concept for {{BRAND}}. Include: emotional narrative, visual style, music direction, voiceover approach, and how it captures brand essence. Business context: {{CHALLENGE}}", whyFits: "Anthems define brand positioning at scale.", howUsed: "Use for major brand launches or repositioning." },
      { id: 10, goal: "TV + Digital Integration", prompt: "Create an integrated TV + digital campaign strategy for {{BRAND}}. Include: TV creative approach, digital extensions (pre-roll, social), sequential messaging, and cross-platform measurement. Goal: {{CHALLENGE}}", whyFits: "Integration multiplies effectiveness.", howUsed: "Brief both TV and digital teams together." }
    ]
  },
  ooh: {
    title: "Out of Home — AI Prompt Library for Marketers",
    summary: "Elite OOH marketers think in bold simplicity and contextual relevance. They understand that outdoor advertising is consumed in seconds—demanding single-minded messaging that leverages location and moment.",
    mentalModels: [
      { name: "The 3-Second Rule", description: "OOH must communicate in 3 seconds or less.", lesson: "If you can't say it in 7 words, it's too long for a billboard.", source: "Outdoor Advertising Association of America" },
      { name: "Context is Creative", description: "Location and timing are part of the message.", lesson: "A gym ad near McDonald's. A coffee ad at 6am. Context multiplies impact.", source: "JCDecaux (2018)" },
      { name: "Priming Effect", description: "OOH creates memory structures activated at point of purchase.", lesson: "Billboard on route to supermarket primes brand choice in store.", source: "IPA Studies (2020)" },
      { name: "The Visual Hammer", description: "Images are processed 60,000x faster than text.", lesson: "Lead with visual, support with minimal text.", source: "Laura Ries, Visual Hammer (2012)" },
      { name: "Sequential Storytelling", description: "Multiple placements can tell a story over time/space.", lesson: "Use different messages on the commute in vs out.", source: "Clear Channel Research (2021)" }
    ],
    prompts: [
      { id: 1, goal: "Billboard Headline Generator", prompt: "Generate 10 billboard headlines for {{BRAND}} in {{INDUSTRY}}. Each must be under 7 words, instantly understandable, and memorable. Include visual concept for each. Business challenge: {{CHALLENGE}}", whyFits: "Brevity is the soul of outdoor.", howUsed: "Test with team for instant comprehension." },
      { id: 2, goal: "Transit Advertising Campaign", prompt: "Design a transit advertising campaign for {{BRAND}}. Include: bus shelter concepts, subway/metro cards, bus wraps, and station domination ideas. Consider dwell time for each format. Context: {{CHALLENGE}}", whyFits: "Transit reaches commuters repeatedly.", howUsed: "Brief creative team and OOH agency." },
      { id: 3, goal: "Digital OOH (DOOH) Strategy", prompt: "Create a Digital OOH strategy for {{BRAND}}. Include: dayparting creative rotations, weather/trigger-based creative, programmatic DOOH approach, and dynamic content ideas. Goal: {{CHALLENGE}}", whyFits: "DOOH enables contextual relevance.", howUsed: "Brief DOOH vendors and creative team." },
      { id: 4, goal: "Location-Based OOH Targeting", prompt: "Develop a location strategy for {{BRAND}}'s OOH campaign. Identify: high-value locations (competitive conquesting, point of purchase, lifestyle), format recommendations per location, and timing. Context: {{CHALLENGE}}", whyFits: "Location multiplies message relevance.", howUsed: "Brief media planner with location rationale." },
      { id: 5, goal: "Ambient/Guerrilla Concepts", prompt: "Generate 5 ambient/guerrilla advertising concepts for {{BRAND}}. Each should be: unexpected, shareable, brand-relevant, and feasible. Include photo-op potential and earned media strategy. Challenge: {{CHALLENGE}}", whyFits: "Ambient creates social sharing.", howUsed: "Evaluate for PR potential and feasibility." },
      { id: 6, goal: "Airport Advertising Strategy", prompt: "Design an airport advertising campaign for {{BRAND}} targeting business travelers. Include: touchpoint mapping (arrivals, gates, lounges), creative concepts per location, and dwell time optimization. Goal: {{CHALLENGE}}", whyFits: "Airports offer captive, affluent audiences.", howUsed: "Brief airport media specialists." },
      { id: 7, goal: "Retail/Point of Sale OOH", prompt: "Create point-of-sale OOH concepts for {{BRAND}}. Include: parking lot signage, store approach, shopping cart/basket ads, and in-store digital screens. Focus on last-mile influence. Context: {{CHALLENGE}}", whyFits: "POS OOH influences purchase at the moment.", howUsed: "Brief retail partners and shopper marketing." },
      { id: 8, goal: "Event/Experiential OOH", prompt: "Design an OOH presence for {{BRAND}} at major events (sports, festivals, conferences). Include: large format concepts, interactive installations, sampling integration, and social amplification. Goal: {{CHALLENGE}}", whyFits: "Events combine reach with engagement.", howUsed: "Brief experiential agency and OOH vendor." },
      { id: 9, goal: "Sequential OOH Storytelling", prompt: "Create a sequential OOH campaign for {{BRAND}} that tells a story across multiple touchpoints. Design 3-5 connected executions that work individually but build together. Context: {{CHALLENGE}}", whyFits: "Sequential messaging builds over time.", howUsed: "Map to commuter journeys and purchase paths." },
      { id: 10, goal: "OOH + Mobile Integration", prompt: "Design an OOH + mobile integration strategy for {{BRAND}}. Include: QR codes, NFC, geofencing around OOH locations, and retargeting strategy. Measure: attribution approach. Challenge: {{CHALLENGE}}", whyFits: "Mobile closes the loop on OOH.", howUsed: "Brief mobile team and OOH vendor together." }
    ]
  },
  podcast: {
    title: "Podcast/Audio — AI Prompt Library for Marketers",
    summary: "Elite audio marketers understand the intimate nature of the medium. They leverage host relationships, create for the 'audio-only' context, and build frequency through sponsorship—knowing that podcast listeners are highly engaged and action-oriented.",
    mentalModels: [
      { name: "Host Endorsement Premium", description: "Host-read ads outperform produced spots by 3x.", lesson: "Invest in host relationships and authentic integration.", source: "Edison Research (2023)" },
      { name: "The Intimacy Advantage", description: "Podcasts are 1:1 conversations in listeners' ears.", lesson: "Write like you're talking to one person, not an audience.", source: "NPR Sponsorship Research (2021)" },
      { name: "Frequency Builds Trust", description: "Podcast sponsorships work through repetition.", lesson: "3-month minimum commitments outperform one-offs.", source: "Midroll (2020)" },
      { name: "Audio-First Creative", description: "Audio must paint pictures without visuals.", lesson: "Describe, don't just tell. Sound design creates world.", source: "Spotify Ad Studio (2022)" },
      { name: "The 'Second Screen' Listener", description: "Most podcast listeners are doing something else.", lesson: "Repeat key information. Don't rely on visual CTAs.", source: "Podcast Insights (2023)" }
    ],
    prompts: [
      { id: 1, goal: "Host-Read Ad Script", prompt: "Write 3 host-read podcast ad scripts for {{BRAND}} (60, 30, and 15 seconds). Include: personal hook, key benefits, offer, and verbal CTA with easy-to-remember URL. Make it sound conversational, not scripted. Context: {{CHALLENGE}}", whyFits: "Host-read ads feel like recommendations.", howUsed: "Send to podcast hosts with talking points." },
      { id: 2, goal: "Podcast Sponsorship Strategy", prompt: "Develop a podcast sponsorship strategy for {{BRAND}} in {{INDUSTRY}}. Include: target podcast criteria, recommended shows, sponsorship tier (pre-roll/mid-roll), frequency recommendations, and budget allocation. Goal: {{CHALLENGE}}", whyFits: "Strategic podcast selection drives efficiency.", howUsed: "Brief media agency or direct outreach." },
      { id: 3, goal: "Produced Audio Ad (60 Seconds)", prompt: "Write a produced 60-second audio ad for {{BRAND}}. Include: sound design direction, voice casting notes, music style, and full script with timing cues. Create for audio-only consumption. Context: {{CHALLENGE}}", whyFits: "Produced ads work for programmatic audio.", howUsed: "Brief audio production team." },
      { id: 4, goal: "Podcast Partnership Pitch", prompt: "Create a partnership pitch for {{BRAND}} to approach podcast hosts. Include: why this partnership makes sense, value proposition for their audience, integration ideas beyond ads, and co-marketing opportunities. Challenge: {{CHALLENGE}}", whyFits: "Deep partnerships drive better performance.", howUsed: "Customize for top 5 target shows." },
      { id: 5, goal: "Audio Brand Guidelines", prompt: "Develop audio brand guidelines for {{BRAND}}. Include: voice characteristics, music direction, sound logo concepts, sonic mnemonic ideas, and examples of on-brand vs off-brand audio. Context: {{CHALLENGE}}", whyFits: "Sonic branding builds recognition.", howUsed: "Share with all audio production partners." },
      { id: 6, goal: "Streaming Audio Strategy", prompt: "Create a streaming audio strategy for {{BRAND}} across Spotify, Pandora, and other platforms. Include: targeting approach, ad formats (audio, video, display), frequency caps, and playlist sponsorship opportunities. Goal: {{CHALLENGE}}", whyFits: "Streaming reaches audio audiences at scale.", howUsed: "Brief programmatic audio team." },
      { id: 7, goal: "Branded Podcast Concept", prompt: "Develop a branded podcast concept for {{BRAND}} in {{INDUSTRY}}. Include: show premise, format (interview, narrative, etc.), episode arc, host profile, and promotion strategy. Business goal: {{CHALLENGE}}", whyFits: "Branded podcasts build thought leadership.", howUsed: "Pitch to leadership or agency partner." },
      { id: 8, goal: "Audio Attribution Framework", prompt: "Design an attribution framework for {{BRAND}}'s audio advertising. Include: tracking methods (vanity URLs, promo codes, post-listen surveys), lift studies, and cross-channel attribution approach. Context: {{CHALLENGE}}", whyFits: "Audio measurement requires creativity.", howUsed: "Set up before campaign launch." },
      { id: 9, goal: "Dynamic Audio Creative", prompt: "Create a dynamic audio ad concept for {{BRAND}} that personalizes based on: time of day, weather, location, or listener data. Include: variable scripts and triggers for each variation. Goal: {{CHALLENGE}}", whyFits: "Dynamic creative increases relevance.", howUsed: "Brief programmatic audio partner." },
      { id: 10, goal: "Voice Assistant Strategy", prompt: "Develop a voice assistant strategy for {{BRAND}} (Alexa, Google Assistant). Include: skill/action concepts, branded voice responses, audio shopping opportunities, and voice SEO recommendations. Context: {{CHALLENGE}}", whyFits: "Voice is the next audio frontier.", howUsed: "Brief voice development team." }
    ]
  }
};
