import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service — Amplify',
  description: 'Terms of Service for Amplify by Fabrica Collective',
}

export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-[#0D0D0D] px-6 py-16 sm:px-10">
      <div className="mx-auto max-w-3xl">

        {/* Back link */}
        <Link
          href="/"
          className="inline-block text-sm text-[#FF0066] hover:text-[#FFFF00] transition-colors mb-10"
        >
          &larr; Back to Amplify
        </Link>

        {/* Page heading */}
        <h1 className="font-display text-4xl sm:text-5xl text-white tracking-wide uppercase mb-3">
          Terms of Service
        </h1>
        <p className="text-[#aaa] text-sm mb-2">
          Last updated: February 2026
        </p>
        <p className="text-[#aaa] text-sm mb-10">
          These Terms of Service (&quot;Terms&quot;) govern your access to and use of <span className="text-white">Amplify</span> (&quot;Service&quot;), operated by <span className="text-white">Fabrica Collective</span> (&quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.
        </p>

        <div className="border-t border-[#333] mb-10" />

        {/* --- Section 1 --- */}
        <section className="mb-10">
          <h2 className="font-display text-xl sm:text-2xl text-[#FF0066] tracking-wide uppercase mb-4">
            1. Service Description &amp; Eligibility
          </h2>
          <div className="space-y-3 text-[#aaa] text-sm leading-relaxed">
            <p>
              Amplify is an AI-powered marketing platform that helps users create marketing strategies and content. The Service uses artificial intelligence&mdash;primarily Google Gemini, with optional support for OpenAI and Anthropic via user-provided API keys&mdash;to generate marketing briefs, campaign strategies, creative ideas, and content.
            </p>
            <p>
              You must be at least <span className="text-white">13 years of age</span> to use the Service. By using Amplify, you represent that you meet this requirement. If you are under 18, you represent that your parent or legal guardian has reviewed and agreed to these Terms.
            </p>
            <p>
              The Service is provided <span className="text-white">&quot;as-is&quot;</span> and <span className="text-white">&quot;as-available.&quot;</span> All content generated by the Service is AI-produced and has not been reviewed, verified, or endorsed by any human at Fabrica Collective.
            </p>
          </div>
        </section>

        <div className="border-t border-[#333] mb-10" />

        {/* --- Section 2 --- */}
        <section className="mb-10">
          <h2 className="font-display text-xl sm:text-2xl text-[#FF0066] tracking-wide uppercase mb-4">
            2. User Accounts
          </h2>
          <div className="space-y-3 text-[#aaa] text-sm leading-relaxed">
            <p>
              Some features of Amplify are available without an account (Anonymous tier: 10 free prompts). Creating an account unlocks additional features and higher usage limits.
            </p>
            <p>When you create an account, you agree to:</p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li>Provide accurate, current, and complete information</li>
              <li>Maintain only one account per person</li>
              <li>Keep your login credentials secure and confidential</li>
              <li>Notify us promptly of any unauthorized access to your account</li>
            </ul>
            <p>
              You are solely responsible for all activity that occurs under your account. Fabrica Collective is not liable for any loss or damage arising from unauthorized use of your credentials.
            </p>
          </div>
        </section>

        <div className="border-t border-[#333] mb-10" />

        {/* --- Section 3 --- */}
        <section className="mb-10">
          <h2 className="font-display text-xl sm:text-2xl text-[#FF0066] tracking-wide uppercase mb-4">
            3. Acceptable Use
          </h2>
          <div className="space-y-3 text-[#aaa] text-sm leading-relaxed">
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li>Generate illegal, harmful, threatening, abusive, defamatory, or otherwise objectionable content</li>
              <li>Produce spam, phishing material, or deceptive marketing content</li>
              <li>Create content that harasses, discriminates against, or incites violence toward any individual or group</li>
              <li>Reverse engineer, decompile, or disassemble any part of the Service</li>
              <li>Scrape, crawl, or use automated tools to extract data from the Service</li>
              <li>Circumvent usage limits, rate limiting, or authentication mechanisms</li>
              <li>Interfere with or disrupt the Service or its infrastructure</li>
              <li>Impersonate any person or entity</li>
            </ul>
            <p>
              You are solely responsible for any content you generate using the Service and any consequences of publishing, distributing, or otherwise using that content. Fabrica Collective does not review, approve, or endorse user-generated outputs.
            </p>
          </div>
        </section>

        <div className="border-t border-[#333] mb-10" />

        {/* --- Section 4 --- */}
        <section className="mb-10">
          <h2 className="font-display text-xl sm:text-2xl text-[#FF0066] tracking-wide uppercase mb-4">
            4. Plans &amp; Payment Terms
          </h2>
          <div className="space-y-3 text-[#aaa] text-sm leading-relaxed">
            <p>Amplify offers the following tiers:</p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li><span className="text-white">Anonymous:</span> 10 free prompts, no signup required</li>
              <li><span className="text-white">Free:</span> 25 prompts per month with a registered account</li>
              <li><span className="text-white">Premium:</span> $29/month, unlimited prompts, billed via Stripe</li>
              <li><span className="text-white">BYOK (Bring Your Own Key):</span> Unlimited prompts using your own API key from a supported provider</li>
            </ul>
            <p className="font-medium text-white text-xs uppercase tracking-wider mt-4 mb-2">Premium Subscription Terms</p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li>Premium subscriptions are billed monthly at $29/month through Stripe. Annual billing may be offered at a discounted rate.</li>
              <li>You may cancel your subscription at any time. Upon cancellation, you retain access to Premium features until the end of your current billing period.</li>
              <li>No refunds are issued for partial billing periods.</li>
              <li>If a payment fails, we may retry the charge. Continued payment failure may result in an automatic downgrade to the Free tier.</li>
              <li>We reserve the right to change pricing with at least <span className="text-white">30 days&apos; written notice</span>. Continued use after a price change constitutes acceptance of the new pricing.</li>
            </ul>
          </div>
        </section>

        <div className="border-t border-[#333] mb-10" />

        {/* --- Section 5 --- */}
        <section className="mb-10">
          <h2 className="font-display text-xl sm:text-2xl text-[#FF0066] tracking-wide uppercase mb-4">
            5. Intellectual Property
          </h2>
          <div className="space-y-3 text-[#aaa] text-sm leading-relaxed">
            <p className="font-medium text-white text-xs uppercase tracking-wider mb-2">Your Content</p>
            <p>
              You retain all rights to the input data you provide to the Service, including your projects, brand information, campaign details, and any other materials you upload or enter.
            </p>
            <p>
              You own the outputs generated by the Service based on your inputs, subject to the terms and policies of the underlying AI providers (Google, OpenAI, Anthropic). It is your responsibility to review the applicable AI provider&apos;s terms regarding ownership of AI-generated content.
            </p>
            <p className="font-medium text-white text-xs uppercase tracking-wider mt-4 mb-2">Our Platform</p>
            <p>
              Fabrica Collective retains all rights, title, and interest in and to the Amplify platform, including its design, code, prompt frameworks, strategic methodology, user interface, and all underlying intellectual property. Nothing in these Terms grants you any right to our proprietary technology beyond the limited right to use the Service as described herein.
            </p>
            <p className="font-medium text-white text-xs uppercase tracking-wider mt-4 mb-2">License to Process</p>
            <p>
              By using the Service, you grant Fabrica Collective a limited, non-exclusive, revocable license to process your input data solely for the purpose of providing the Service to you. We do not use your data to train models or for any purpose beyond delivering the Service.
            </p>
          </div>
        </section>

        <div className="border-t border-[#333] mb-10" />

        {/* --- Section 6 --- */}
        <section className="mb-10">
          <h2 className="font-display text-xl sm:text-2xl text-[#FF0066] tracking-wide uppercase mb-4">
            6. AI-Generated Content Disclaimer
          </h2>
          <div className="space-y-3 text-[#aaa] text-sm leading-relaxed">
            <p>
              All content produced by Amplify is generated by artificial intelligence. It is not reviewed, edited, or verified by any human at Fabrica Collective. You acknowledge and agree that:
            </p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li>AI-generated content may contain inaccuracies, errors, biases, or outdated information</li>
              <li>There is no guarantee of originality&mdash;outputs may resemble content generated for other users or content that exists elsewhere</li>
              <li>No warranty of fitness for any particular purpose is made regarding generated content</li>
              <li>You are responsible for reviewing, fact-checking, and editing all outputs before use</li>
              <li>You are responsible for ensuring any content you publish complies with applicable advertising standards, regulations, and laws in your jurisdiction</li>
              <li>Fabrica Collective is not liable for any claims, damages, or losses arising from your reliance on or use of AI-generated content</li>
            </ul>
          </div>
        </section>

        <div className="border-t border-[#333] mb-10" />

        {/* --- Section 7 --- */}
        <section className="mb-10">
          <h2 className="font-display text-xl sm:text-2xl text-[#FF0066] tracking-wide uppercase mb-4">
            7. Third-Party Services
          </h2>
          <div className="space-y-3 text-[#aaa] text-sm leading-relaxed">
            <p>
              The Service relies on third-party providers to operate, including but not limited to:
            </p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li><span className="text-white">Google Gemini</span> &mdash; AI content generation</li>
              <li><span className="text-white">OpenAI / Anthropic</span> &mdash; Optional AI providers (BYOK)</li>
              <li><span className="text-white">Stripe</span> &mdash; Payment processing</li>
              <li><span className="text-white">Supabase</span> &mdash; Authentication and database</li>
              <li><span className="text-white">Vercel</span> &mdash; Hosting and deployment</li>
              <li><span className="text-white">Cloudflare</span> &mdash; Security and CDN</li>
            </ul>
            <p>
              By using Amplify, you also agree to be bound by the terms of service and privacy policies of these third-party providers to the extent they apply to your use of the Service. Fabrica Collective is not responsible for outages, errors, data handling, or policy changes by any third-party provider.
            </p>
          </div>
        </section>

        <div className="border-t border-[#333] mb-10" />

        {/* --- Section 8 --- */}
        <section className="mb-10">
          <h2 className="font-display text-xl sm:text-2xl text-[#FF0066] tracking-wide uppercase mb-4">
            8. Data &amp; Privacy
          </h2>
          <div className="space-y-3 text-[#aaa] text-sm leading-relaxed">
            <p>
              Your use of the Service is also governed by our{' '}
              <Link href="/privacy" className="text-[#FF0066] hover:text-[#FFFF00] transition-colors underline">
                Privacy Policy
              </Link>
              , which describes how we collect, use, store, and protect your data.
            </p>
            <p>
              By using the Service, you acknowledge that the marketing briefs, strategies, brand information, and other content you provide may be sent to the Google Gemini API (or other selected AI provider) for processing. This transmission is necessary to deliver the Service and is performed in accordance with our Privacy Policy.
            </p>
          </div>
        </section>

        <div className="border-t border-[#333] mb-10" />

        {/* --- Section 9 --- */}
        <section className="mb-10">
          <h2 className="font-display text-xl sm:text-2xl text-[#FF0066] tracking-wide uppercase mb-4">
            9. Limitation of Liability
          </h2>
          <div className="space-y-3 text-[#aaa] text-sm leading-relaxed">
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE IS PROVIDED &quot;AS-IS&quot; AND &quot;AS-AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, OR NON-INFRINGEMENT.
            </p>
            <p>
              FABRICA COLLECTIVE DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE OF HARMFUL COMPONENTS.
            </p>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, FABRICA COLLECTIVE&apos;S TOTAL AGGREGATE LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR USE OF THE SERVICE SHALL NOT EXCEED THE TOTAL AMOUNT OF FEES YOU HAVE PAID TO US IN THE <span className="text-white">TWELVE (12) MONTHS</span> IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR <span className="text-white">$100</span>, WHICHEVER IS GREATER.
            </p>
            <p>
              IN NO EVENT SHALL FABRICA COLLECTIVE BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, BUSINESS OPPORTUNITIES, GOODWILL, OR REPUTATION, REGARDLESS OF THE THEORY OF LIABILITY, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
          </div>
        </section>

        <div className="border-t border-[#333] mb-10" />

        {/* --- Section 10 --- */}
        <section className="mb-10">
          <h2 className="font-display text-xl sm:text-2xl text-[#FF0066] tracking-wide uppercase mb-4">
            10. Indemnification
          </h2>
          <div className="space-y-3 text-[#aaa] text-sm leading-relaxed">
            <p>
              You agree to indemnify, defend, and hold harmless Fabrica Collective, its officers, directors, employees, agents, and affiliates from and against any claims, liabilities, damages, losses, costs, and expenses (including reasonable attorneys&apos; fees) arising out of or in connection with:
            </p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li>Your use of the Service</li>
              <li>Content you generate, publish, or distribute using the Service</li>
              <li>Your violation of these Terms</li>
              <li>Your violation of any applicable law or regulation</li>
              <li>Your infringement of any third-party right, including intellectual property rights</li>
            </ul>
          </div>
        </section>

        <div className="border-t border-[#333] mb-10" />

        {/* --- Section 11 --- */}
        <section className="mb-10">
          <h2 className="font-display text-xl sm:text-2xl text-[#FF0066] tracking-wide uppercase mb-4">
            11. Termination
          </h2>
          <div className="space-y-3 text-[#aaa] text-sm leading-relaxed">
            <p>
              <span className="text-white">By You:</span> You may delete your account at any time through the Service. Upon deletion, your active Stripe subscription (if any) will be cancelled.
            </p>
            <p>
              <span className="text-white">By Us:</span> We reserve the right to suspend or terminate your account at any time, with or without notice, if we reasonably believe you have violated these Terms or if your use poses a risk to the Service or other users.
            </p>
            <p>
              <span className="text-white">Effect of Termination:</span> Upon termination, your right to use the Service ceases immediately. Any active subscription will be cancelled, and no refund will be issued for the remaining billing period. Your data will be retained for up to <span className="text-white">30 days</span> following termination to allow for data export requests, after which it will be permanently deleted in accordance with our Privacy Policy.
            </p>
            <p>
              Sections 5, 6, 9, 10, and 12 shall survive termination of these Terms.
            </p>
          </div>
        </section>

        <div className="border-t border-[#333] mb-10" />

        {/* --- Section 12 --- */}
        <section className="mb-10">
          <h2 className="font-display text-xl sm:text-2xl text-[#FF0066] tracking-wide uppercase mb-4">
            12. General Provisions
          </h2>
          <div className="space-y-3 text-[#aaa] text-sm leading-relaxed">
            <p>
              <span className="text-white">Governing Law.</span> These Terms are governed by and construed in accordance with the laws of the State of California, United States, without regard to its conflict of law provisions.
            </p>
            <p>
              <span className="text-white">Dispute Resolution.</span> Any dispute arising out of or relating to these Terms or the Service shall be resolved by binding arbitration administered in the State of California, in accordance with the rules of the American Arbitration Association. You agree to waive any right to a jury trial or to participate in a class action. Notwithstanding the foregoing, either party may seek injunctive or other equitable relief in any court of competent jurisdiction.
            </p>
            <p>
              <span className="text-white">Entire Agreement.</span> These Terms, together with our Privacy Policy, constitute the entire agreement between you and Fabrica Collective regarding the Service and supersede all prior agreements and understandings.
            </p>
            <p>
              <span className="text-white">Severability.</span> If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary, and the remaining provisions shall remain in full force and effect.
            </p>
            <p>
              <span className="text-white">Assignment.</span> You may not assign or transfer these Terms or your rights hereunder without our prior written consent. We may assign these Terms without restriction.
            </p>
            <p>
              <span className="text-white">Waiver.</span> Our failure to enforce any right or provision of these Terms shall not constitute a waiver of that right or provision.
            </p>
            <p>
              <span className="text-white">Changes to Terms.</span> We reserve the right to modify these Terms at any time. Material changes will be communicated via email or a prominent notice on the Service. Your continued use of the Service after such notice constitutes acceptance of the revised Terms.
            </p>
          </div>
        </section>

        <div className="border-t border-[#333] mb-10" />

        {/* --- Contact --- */}
        <section className="mb-16">
          <h2 className="font-display text-xl sm:text-2xl text-white tracking-wide uppercase mb-4">
            Contact
          </h2>
          <div className="text-[#aaa] text-sm leading-relaxed space-y-2">
            <p>
              If you have any questions about these Terms, please contact us at:
            </p>
            <p>
              <a
                href="mailto:Admin@FabricaCollective.com"
                className="text-[#FF0066] hover:text-[#FFFF00] transition-colors"
              >
                Admin@FabricaCollective.com
              </a>
            </p>
            <p className="text-[#555] text-xs mt-6">
              Fabrica Collective &middot; amplify.fabricacollective.com
            </p>
          </div>
        </section>

      </div>
    </main>
  )
}
